-- Web Push: one row per browser/device a signed-in user has allowed.
create table if not exists public.push_subscriptions (
  endpoint    text primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  p256dh      text not null default '',
  auth        text not null default '',
  created_at  timestamptz not null default now(),
  last_sent_at timestamptz
);

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions (user_id);

alter table public.push_subscriptions enable row level security;

drop policy if exists "push subs select own" on public.push_subscriptions;
create policy "push subs select own" on public.push_subscriptions
  for select using (auth.uid() = user_id);

drop policy if exists "push subs insert own" on public.push_subscriptions;
create policy "push subs insert own" on public.push_subscriptions
  for insert with check (auth.uid() = user_id);

drop policy if exists "push subs update own" on public.push_subscriptions;
create policy "push subs update own" on public.push_subscriptions
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "push subs delete own" on public.push_subscriptions;
create policy "push subs delete own" on public.push_subscriptions
  for delete using (auth.uid() = user_id);

-- VAPID keypair. Generated by the push-key edge function on first call so
-- the private key is never typed by hand or pasted into a transcript.
-- Service role only: no client policies, and grants revoked below.
create table if not exists public.push_config (
  id          smallint primary key default 1 check (id = 1),
  public_key  text not null,
  private_key text not null,
  subject     text not null default 'mailto:vanwykkelvin16@gmail.com',
  created_at  timestamptz not null default now()
);

alter table public.push_config enable row level security;
revoke all on public.push_config from anon, authenticated;
grant select, insert, update on public.push_config to service_role;
